import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { M_PLUS_Rounded_1c } from 'next/font/google'
import "./globals.css";
import { Providers } from "./providers"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mplus = M_PLUS_Rounded_1c({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mplus.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
